# pnpm-workspace.yaml
packages:
  # all packages in sub dirs of packages/ and apps/
  - "libs/**"
  - "apps/**"

ignoreDepScripts: true
ignoreWorkspaceRootCheck: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
  - vue-demi

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - rollup@2.80.0
  - semver@6.3.1

onlyBuiltDependencies:
  - better-sqlite3
  - sharp