packages:
  # all packages in sub dirs of packages/ and apps/
  - "libs/**"
  - "apps/**"

ignoreWorkspaceRootCheck: true

trustPolicyExclude:
  - chokidar@4.0.3
  - rollup@2.80.0
  - semver@6.3.1
  - xlsx@0.20.3

catalogs:
  default:
    # Production Dependencies - Framework, UI, Utilities
    nuxt: "^4.6.1"
    vue: "^3.5.43"
    "@nuxt/ui": "^4.11.3"
    "@nuxt/image": "^2.1.0"
    "@nuxtjs/i18n": "^10.6.0"
    "@vueuse/core": "^15.0.0"
    "@number-flow/vue": "^0.5.2"
    "@pinia/nuxt": "^1.0.2"
    date-fns: "^4.4.0"
    zod: "^4.6.5"
    # WebAuthn
    "@simplewebauthn/browser": "^14.0.0"
    "@simplewebauthn/server": "^14.0.0"
    # Other dependencies
    "qrcode.vue": "^3.11.0"
    "@vue-email/components": "^0.0.21"
    "drizzle-orm": "^0.45.3"
    pg: "^8.23.1"

  dev:
    # Development Dependencies - Tooling, Types, Testing
    typescript: "^7.0.2"
    "@types/node": "^24.19.1"
    "@nuxt/hints": "^1.1.4"
    nuxt-security: "^2.6.0"
    "@iconify-json/lucide": "^1.2.141"
    "@iconify-json/ri": "^1.2.10"
    drizzle-kit: "^0.31.11"

overrides:
  "zod": "^4.6.5"
  "@netlify/functions": "-"
  "@netlify/blobs": "-"

shamefullyHoist: true
reporter: append-only

allowBuilds:
  better-sqlite3: true
  sharp: true
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

minimumReleaseAgeExclude:
  - "@nuxt/cli@4.0.1"
  - "@nuxt/kit@4.6.1"
  - "@nuxt/nitro-server@4.6.1"
  - "@nuxt/schema@4.6.1"
  - "@nuxt/vite-builder@4.6.1"
  - "@nuxt/vite-server@4.6.1"
  - nuxt@4.6.1
