name: CI

on:
  push:
    branches:
      - "**"

permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run build
        run: pnpm build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Lint
        run: pnpm lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Tests
        run: pnpm test

      - name: Upload coverage report
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-code-coverage@v1
        with:
          file: coverage/cobertura-coverage.xml
          language: JavaScript
          label: coverage-report

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Typecheck
        continue-on-error: true
        run: pnpm -r typecheck
